# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61894ebb35620ae9464291de66d6f01e9ecd08055ed8ff57092f608021ab220f570efc96ed777d5832f5e6ec9bae108c790d608f9156590ccf7c6f0178d82472
  facebook_app_id: <%= ENV["IN_APP_ID"] %>
  facebook_app_secret: <%= ENV["IN_SECRET"] %>
test:
  secret_key_base: 888a172792752e39f1ed47ba9f14d7dccfd3024d04ce3d4811d8660a693d7264081f74c4799ef13024d6d592581fda0edd849d1a335d65b42356debd553332b1
  facebook_app_id: <%= ENV["IN_APP_ID"] %>
  facebook_app_secret: <%= ENV["IN_SECRET"] %>
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: <%= ENV["IN_APP_ID"] %>
  facebook_app_secret: <%= ENV["IN_SECRET"] %>
